#что такое Yaml Anchors
# - &flag Apple
# - Beachball
# - Cartoon
# - Duckface
# - *flag
# - *flag

# docker-compose help
# docker-compose config
version: "3"
# The parser will ignore extension fields prefixed with x-
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 256M
      reservations:
        memory: 128M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 

services:
  mysql:
    image: mariadb:10.6.4-focal
    #user: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    networks: ["wordpress"]
    ports: ["127.0.0.1:3306:3306"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # profiles:
    #   - base
    #   - prod 
  wordpress:
    depends_on: ["mysql"]
    image: wordpress:php8.2-apache
    #user: wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    networks: ["wordpress"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=mysql
    # profiles:
    #   - base
    #   - prod 
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://127.0.0.1/wp-admin/install.php/ | grep 'Продолжить' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 2
  nginx:

    build:
      context: /opt/
    # profiles:
    #   - base
    #   - prod



volumes:
  db_data: {}
  wp_data: {}
networks:
  wordpress:
    name: wordpress
    netmask: 172.16.5.0/24

